version: 2

sources:
  - name: raw
    project: f1-analytics-pipeline
    dataset: raw
    tables:
      - name: race_results
      - name: race_laps
      - name: race_weather
      - name: drivers
      - name: constructors
      - name: driver_standings
      - name: constructor_standings
